#!/bin/bash
# author : Chris Feldmeier
# 2016

if [ $(whoami) != "root" ]; then
    echo "Elassandra bash script works only with root user"
    exit 1
fi

CASSANDRADIR=/etc/elassandra/bin
PIDFILE=/var/run/elassandra.pid
LOGFILE=/var/log/elassandra/output_script.log
USER=root
_BOLD=`tput bold`
_NORMAL=`tput sgr0`
PARAMS="-p ${PIDFILE}"

writelog(){
    echo "`date` : $1" >> "$LOG"
}

log_clear(){
    echo "`date` - cleared" > $LOG
}

start(){
    if [ ! -f ${PIDFILE} ];
    then
        echo "Starting ${_BOLD}Elassandra (Elasticsearch+Cassandra) ${_NORMAL} ..."
        start-stop-daemon --start \
            --user ${USER} \
            --pidfile ${PIDFILE} \
            --exec ${CASSANDRADIR}/elassandra -- ${PARAMS} \ >> ${LOGFILE}
        sleep 3
        echo "Elassandra started ."
    else
        echo "Elassandra already running !!"
    fi
}

stop(){
    if [ ! -f ${PIDFILE} ] ; then
        echo "Elassandra is ${_BOLD}not${_NORMAL} running"
    else
        echo "Elassandra stopping ... "
        pid_no=`cat ${PIDFILE}`
        kill $pid_no
        rm ${PIDFILE}
        sleep 2
    fi
}

status(){
    if [ ! -f $PIDFILE ] ; then
        echo "Elassandra is ${_BOLD}not${_NORMAL} running"
    else
        echo "Elassandra running. pid : " `cat $PID`
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    logclear)
        log_clear
        ;;
    *)
        echo "Usage : sudo service elassandra (start|stop|restart|status|logclear)"
        ;;
esac

exit 1